# Universal Web Scraper Configuration
# Adapt these settings for different target websites

target:
  base_url: "http://quotes.toscrape.com/"  # Scraping practice site with real content
  max_pages: 3
  delay_range: [1, 3]  # Random delay between requests in seconds
  page_load_timeout: 15

scraping:
  selectors:
    # CSS selectors for quotes.toscrape.com - a good test site
    container: "div.quote"  # Each quote container
    title: "span.text"      # Quote text
    description: "small.author"  # Author name
    link: "a[href*='/author/']"  # Link to author page
    location: "span.text"   # We'll use quote text as location for demo
    revenue: "small.author" # We'll use author as revenue for demo
  
  pagination:
    url_pattern: "{base_url}page/{page_num}/"
    start_page: 1

proxy:
  enabled: false  # Disabled for testing
  max_failures: 3
  rotation_frequency: 5  # Rotate proxy after N pages

output:
  filename: "scraped_data.csv"
  directory: "data"

# Anti-detection settings
stealth:
  random_delays: true
  rotate_user_agents: true
  block_images: true
  headless_mode: true
